version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    hostname: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    links:
      - db
    container_name: backend
    restart: on-failure
    ports:
      - "8080:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      SPOTIFY_TOKEN: ${SPOTIFY_TOKEN}
    depends_on:
      - db

  frontend:
    build: ./frontend/
    links:
      - backend
    container_name: frontend
    ports:
      - "1234:80"
    depends_on:
      - backend

volumes:
  db:
    driver: local