version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    container_name: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    links:
      - db
    container_name: backend
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - db

  frontend:
    build: ./frontend/
    links:
      - backend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db:
    driver: local