spring:

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    show-sql: true
    generate-ddl: true

spotify-api:
  token: // YOUR TOKEN HERE
  paths:
    base-url: https://api.spotify.com/v1/
    search-albums: https://api.spotify.com/v1/search?type=album&q=
    search-album: https://api.spotify.com/v1/albums/
